"""new report table update

Revision ID: 01ab4fbddc72
Revises: e00aeddcd46d
Create Date: 2021-08-09 13:00:02.559217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01ab4fbddc72'
down_revision = 'e00aeddcd46d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_report',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('script', sa.String(length=500), nullable=False),
    sa.Column('useremail', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('useremail')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issue_report')
    # ### end Alembic commands ###
