"""report db update

Revision ID: 103a06a8a61a
Revises: 01ab4fbddc72
Create Date: 2021-08-11 15:23:16.573431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '103a06a8a61a'
down_revision = '01ab4fbddc72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('useremail', table_name='issue_report')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('useremail', 'issue_report', ['useremail'], unique=False)
    # ### end Alembic commands ###
