"""empty message

Revision ID: 2199cfc2fba4
Revises: 
Create Date: 2021-08-03 20:29:34.109269

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2199cfc2fba4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('s21_1', 'id',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=False,
               autoincrement=True)
    op.alter_column('s21_2', 'id',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=False,
               autoincrement=True)
    op.alter_column('s21_s', 'id',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('s21_s', 'id',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=True,
               autoincrement=True)
    op.alter_column('s21_2', 'id',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=True,
               autoincrement=True)
    op.alter_column('s21_1', 'id',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###
