"""user model updated

Revision ID: 35d59200238c
Revises: e73bba32168c
Create Date: 2021-07-24 11:06:53.380398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35d59200238c'
down_revision = 'e73bba32168c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('major', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'major')
    # ### end Alembic commands ###
