"""db update

Revision ID: 6aab73c19cfc
Revises: 
Create Date: 2021-07-31 09:05:33.374600

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6aab73c19cfc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_s21_2_id', table_name='s21_2')
    op.drop_table('s21_2')
    op.add_column('user', sa.Column('verify_on', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('verify_code', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'verify_code')
    op.drop_column('user', 'verify_on')
    op.create_table('s21_2',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('학년도', mysql.TEXT(), nullable=True),
    sa.Column('학기', mysql.TEXT(), nullable=True),
    sa.Column('소속', mysql.TEXT(), nullable=True),
    sa.Column('학과', mysql.TEXT(), nullable=True),
    sa.Column('과목번호', mysql.TEXT(), nullable=True),
    sa.Column('분반', mysql.TEXT(), nullable=True),
    sa.Column('과목명', mysql.TEXT(), nullable=True),
    sa.Column('강의계획서', mysql.TEXT(), nullable=True),
    sa.Column('학점', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('수업시간_강의실', mysql.TEXT(), nullable=True),
    sa.Column('시간', mysql.TEXT(), nullable=True),
    sa.Column('교수진', mysql.TEXT(), nullable=True),
    sa.Column('수강생수', mysql.TEXT(), nullable=True),
    sa.Column('영어강의', mysql.TEXT(), nullable=True),
    sa.Column('중국어강의', mysql.TEXT(), nullable=True),
    sa.Column('공학인증', mysql.TEXT(), nullable=True),
    sa.Column('국제학생', mysql.TEXT(), nullable=True),
    sa.Column('Honors과목', mysql.TEXT(), nullable=True),
    sa.Column('홀짝구분', mysql.TEXT(), nullable=True),
    sa.Column('승인과목', mysql.TEXT(), nullable=True),
    sa.Column('시험일자', mysql.TEXT(), nullable=True),
    sa.Column('수강대상', mysql.TEXT(), nullable=True),
    sa.Column('권장학년', mysql.TEXT(), nullable=True),
    sa.Column('수강신청_참조사항', mysql.TEXT(), nullable=True),
    sa.Column('과목_설명', mysql.TEXT(), nullable=True),
    sa.Column('비고', mysql.TEXT(), nullable=True),
    sa.Column('subject_id', mysql.TEXT(), nullable=True),
    sa.Column('전인교육원', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('요일', mysql.TEXT(), nullable=True),
    sa.Column('시작시간', mysql.TEXT(), nullable=True),
    sa.Column('종료시간', mysql.TEXT(), nullable=True),
    sa.Column('강의실', mysql.TEXT(), nullable=True),
    sa.Column('대면여부', mysql.TEXT(), nullable=True),
    sa.Column('강의언어', mysql.TEXT(), nullable=True),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_s21_2_id', 's21_2', ['id'], unique=False)
    # ### end Alembic commands ###
