"""fix user tables

Revision ID: 97511f53be01
Revises: d18d90552f23
Create Date: 2021-07-24 15:22:18.010916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97511f53be01'
down_revision = 'd18d90552f23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('public_id', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'user', ['public_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'public_id')
    # ### end Alembic commands ###
