"""db update

Revision ID: a2a654836eed
Revises: 55a0ebe68756
Create Date: 2021-08-06 06:01:38.173158

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a2a654836eed'
down_revision = '55a0ebe68756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_complete', sa.Column('subject_id', sa.Text(), nullable=False))
    op.drop_column('user_complete', 'subject_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_complete', sa.Column('subject_code', mysql.TEXT(), nullable=False))
    op.drop_column('user_complete', 'subject_id')
    # ### end Alembic commands ###
