"""db update

Revision ID: a3c04b7a0053
Revises: a2a654836eed
Create Date: 2021-08-07 04:18:47.621289

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a3c04b7a0053'
down_revision = 'a2a654836eed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('allow_email', sa.Boolean(), nullable=False))
    op.drop_index('public_id', table_name='user')
    op.drop_column('user', 'public_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('public_id', mysql.VARCHAR(length=100), nullable=True))
    op.create_index('public_id', 'user', ['public_id'], unique=False)
    op.drop_column('user', 'allow_email')
    # ### end Alembic commands ###
