"""empty message

Revision ID: b80c1fff5642
Revises: 750f5232e59d
Create Date: 2021-08-03 20:42:52.324734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b80c1fff5642'
down_revision = '750f5232e59d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='user_subject')
    op.drop_index('subject_id', table_name='user_subject')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('subject_id', 'user_subject', ['subject_id'], unique=False)
    op.create_index('email', 'user_subject', ['email'], unique=False)
    # ### end Alembic commands ###
