"""add columns and id in total_data

Revision ID: cedd9463f58a
Revises: 
Create Date: 2021-07-25 16:43:30.349386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cedd9463f58a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_index('id', table_name='total_data')
    op.create_index('id', 'total_data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('id', 'total_data', ['id'], unique=False)
    # ### end Alembic commands ###
