"""user model updated

Revision ID: d18d90552f23
Revises: 35d59200238c
Create Date: 2021-07-24 11:53:06.396171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd18d90552f23'
down_revision = '35d59200238c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('username', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('username', 'user', ['username'], unique=False)
    # ### end Alembic commands ###
