"""first migrate

Revision ID: e73bba32168c
Revises: 
Create Date: 2021-07-24 12:27:39.177875

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e73bba32168c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=120), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('s21_2')
    op.drop_table('21-2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('21-2',
    sa.Column('학년도', mysql.TEXT(), nullable=True),
    sa.Column('학기', mysql.TEXT(), nullable=True),
    sa.Column('소속', mysql.TEXT(), nullable=True),
    sa.Column('학과', mysql.TEXT(), nullable=True),
    sa.Column('과목번호', mysql.TEXT(), nullable=True),
    sa.Column('분반', mysql.TEXT(), nullable=True),
    sa.Column('과목명', mysql.TEXT(), nullable=True),
    sa.Column('강의계획서', mysql.TEXT(), nullable=True),
    sa.Column('학점', mysql.TEXT(), nullable=True),
    sa.Column('수업시간/강의실', mysql.TEXT(), nullable=True),
    sa.Column('시간', mysql.TEXT(), nullable=True),
    sa.Column('교수진', mysql.TEXT(), nullable=True),
    sa.Column('수강생수', mysql.TEXT(), nullable=True),
    sa.Column('영어강의', mysql.TEXT(), nullable=True),
    sa.Column('중국어강의', mysql.TEXT(), nullable=True),
    sa.Column('공학인증', mysql.TEXT(), nullable=True),
    sa.Column('국제학생', mysql.TEXT(), nullable=True),
    sa.Column('Honors과목', mysql.TEXT(), nullable=True),
    sa.Column('홀짝구분', mysql.TEXT(), nullable=True),
    sa.Column('승인과목', mysql.TEXT(), nullable=True),
    sa.Column('시험일자', mysql.TEXT(), nullable=True),
    sa.Column('수강대상', mysql.TEXT(), nullable=True),
    sa.Column('권장학년', mysql.TEXT(), nullable=True),
    sa.Column('수강신청 참조사항', mysql.TEXT(), nullable=True),
    sa.Column('과목 설명', mysql.TEXT(), nullable=True),
    sa.Column('비고', mysql.TEXT(), nullable=True),
    sa.Column('subject_id', mysql.TEXT(), nullable=True),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('s21_2',
    sa.Column('학년도', mysql.TEXT(), nullable=True),
    sa.Column('학기', mysql.TEXT(), nullable=True),
    sa.Column('소속', mysql.TEXT(), nullable=True),
    sa.Column('학과', mysql.TEXT(), nullable=True),
    sa.Column('과목번호', mysql.TEXT(), nullable=True),
    sa.Column('분반', mysql.TEXT(), nullable=True),
    sa.Column('과목명', mysql.TEXT(), nullable=True),
    sa.Column('강의계획서', mysql.TEXT(), nullable=True),
    sa.Column('학점', mysql.TEXT(), nullable=True),
    sa.Column('수업시간/강의실', mysql.TEXT(), nullable=True),
    sa.Column('시간', mysql.TEXT(), nullable=True),
    sa.Column('교수진', mysql.TEXT(), nullable=True),
    sa.Column('수강생수', mysql.TEXT(), nullable=True),
    sa.Column('영어강의', mysql.TEXT(), nullable=True),
    sa.Column('중국어강의', mysql.TEXT(), nullable=True),
    sa.Column('공학인증', mysql.TEXT(), nullable=True),
    sa.Column('국제학생', mysql.TEXT(), nullable=True),
    sa.Column('Honors과목', mysql.TEXT(), nullable=True),
    sa.Column('홀짝구분', mysql.TEXT(), nullable=True),
    sa.Column('승인과목', mysql.TEXT(), nullable=True),
    sa.Column('시험일자', mysql.TEXT(), nullable=True),
    sa.Column('수강대상', mysql.TEXT(), nullable=True),
    sa.Column('권장학년', mysql.TEXT(), nullable=True),
    sa.Column('수강신청 참조사항', mysql.TEXT(), nullable=True),
    sa.Column('과목 설명', mysql.TEXT(), nullable=True),
    sa.Column('비고', mysql.TEXT(), nullable=True),
    sa.Column('subject_id', mysql.TEXT(), nullable=True),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('user')
    op.drop_table('blacklist_tokens')
    # ### end Alembic commands ###
